/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface AIDecisionRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decisions"
      | "isRegistered"
      | "registerDecision"
      | "verifyDecision"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DecisionRegistered"): EventFragment;

  encodeFunctionData(
    functionFragment: "decisions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isRegistered",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerDecision",
    values: [BytesLike, BytesLike, string, BytesLike, BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyDecision",
    values: [BytesLike, BytesLike]
  ): string;

  decodeFunctionResult(functionFragment: "decisions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRegistered",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyDecision",
    data: BytesLike
  ): Result;
}

export namespace DecisionRegisteredEvent {
  export type InputTuple = [
    decisionId: BytesLike,
    domainHash: BytesLike,
    chosenModelHash: BytesLike,
    ipfsCidHash: BytesLike,
    subject: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    decisionId: string,
    domainHash: string,
    chosenModelHash: string,
    ipfsCidHash: string,
    subject: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    decisionId: string;
    domainHash: string;
    chosenModelHash: string;
    ipfsCidHash: string;
    subject: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AIDecisionRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AIDecisionRegistry;
  waitForDeployment(): Promise<this>;

  interface: AIDecisionRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decisions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, string, bigint] & {
        decisionId: string;
        ipfsCidHash: string;
        ipfsCid: string;
        domainHash: string;
        chosenModelHash: string;
        subject: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  isRegistered: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  registerDecision: TypedContractMethod<
    [
      _decisionId: BytesLike,
      _ipfsCidHash: BytesLike,
      _ipfsCid: string,
      _domainHash: BytesLike,
      _chosenModelHash: BytesLike,
      _subject: string
    ],
    [void],
    "nonpayable"
  >;

  verifyDecision: TypedContractMethod<
    [_decisionId: BytesLike, _ipfsCidHash: BytesLike],
    [boolean],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decisions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, string, string, string, bigint] & {
        decisionId: string;
        ipfsCidHash: string;
        ipfsCid: string;
        domainHash: string;
        chosenModelHash: string;
        subject: string;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRegistered"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerDecision"
  ): TypedContractMethod<
    [
      _decisionId: BytesLike,
      _ipfsCidHash: BytesLike,
      _ipfsCid: string,
      _domainHash: BytesLike,
      _chosenModelHash: BytesLike,
      _subject: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyDecision"
  ): TypedContractMethod<
    [_decisionId: BytesLike, _ipfsCidHash: BytesLike],
    [boolean],
    "view"
  >;

  getEvent(
    key: "DecisionRegistered"
  ): TypedContractEvent<
    DecisionRegisteredEvent.InputTuple,
    DecisionRegisteredEvent.OutputTuple,
    DecisionRegisteredEvent.OutputObject
  >;

  filters: {
    "DecisionRegistered(bytes32,bytes32,bytes32,bytes32,string,uint256)": TypedContractEvent<
      DecisionRegisteredEvent.InputTuple,
      DecisionRegisteredEvent.OutputTuple,
      DecisionRegisteredEvent.OutputObject
    >;
    DecisionRegistered: TypedContractEvent<
      DecisionRegisteredEvent.InputTuple,
      DecisionRegisteredEvent.OutputTuple,
      DecisionRegisteredEvent.OutputObject
    >;
  };
}
