/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace DecisionLogger {
  export type DecisionStruct = {
    decisionId: BytesLike;
    decisionHash: BytesLike;
    modelHash: BytesLike;
    ftsoRoundId: BigNumberish;
    fdcProofHash: BytesLike;
    timestamp: BigNumberish;
    backendSigner: AddressLike;
  };

  export type DecisionStructOutput = [
    decisionId: string,
    decisionHash: string,
    modelHash: string,
    ftsoRoundId: bigint,
    fdcProofHash: string,
    timestamp: bigint,
    backendSigner: string
  ] & {
    decisionId: string;
    decisionHash: string;
    modelHash: string;
    ftsoRoundId: bigint;
    fdcProofHash: string;
    timestamp: bigint;
    backendSigner: string;
  };
}

export interface DecisionLoggerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "decisions"
      | "getDecision"
      | "isDecisionLogged"
      | "logDecision"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "DecisionLogged"): EventFragment;

  encodeFunctionData(
    functionFragment: "decisions",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDecision",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isDecisionLogged",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logDecision",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BigNumberish,
      BytesLike,
      BigNumberish,
      AddressLike
    ]
  ): string;

  decodeFunctionResult(functionFragment: "decisions", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDecision",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDecisionLogged",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "logDecision",
    data: BytesLike
  ): Result;
}

export namespace DecisionLoggedEvent {
  export type InputTuple = [
    decisionId: BytesLike,
    decisionHash: BytesLike,
    backendSigner: AddressLike,
    timestamp: BigNumberish,
    ftsoRoundId: BigNumberish,
    fdcProofHash: BytesLike
  ];
  export type OutputTuple = [
    decisionId: string,
    decisionHash: string,
    backendSigner: string,
    timestamp: bigint,
    ftsoRoundId: bigint,
    fdcProofHash: string
  ];
  export interface OutputObject {
    decisionId: string;
    decisionHash: string;
    backendSigner: string;
    timestamp: bigint;
    ftsoRoundId: bigint;
    fdcProofHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DecisionLogger extends BaseContract {
  connect(runner?: ContractRunner | null): DecisionLogger;
  waitForDeployment(): Promise<this>;

  interface: DecisionLoggerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  decisions: TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, bigint, string] & {
        decisionId: string;
        decisionHash: string;
        modelHash: string;
        ftsoRoundId: bigint;
        fdcProofHash: string;
        timestamp: bigint;
        backendSigner: string;
      }
    ],
    "view"
  >;

  getDecision: TypedContractMethod<
    [_decisionId: BytesLike],
    [DecisionLogger.DecisionStructOutput],
    "view"
  >;

  isDecisionLogged: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  logDecision: TypedContractMethod<
    [
      _decisionId: BytesLike,
      _decisionHash: BytesLike,
      _modelHash: BytesLike,
      _ftsoRoundId: BigNumberish,
      _fdcProofHash: BytesLike,
      _timestamp: BigNumberish,
      _backendSigner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "decisions"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [string, string, string, bigint, string, bigint, string] & {
        decisionId: string;
        decisionHash: string;
        modelHash: string;
        ftsoRoundId: bigint;
        fdcProofHash: string;
        timestamp: bigint;
        backendSigner: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDecision"
  ): TypedContractMethod<
    [_decisionId: BytesLike],
    [DecisionLogger.DecisionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isDecisionLogged"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logDecision"
  ): TypedContractMethod<
    [
      _decisionId: BytesLike,
      _decisionHash: BytesLike,
      _modelHash: BytesLike,
      _ftsoRoundId: BigNumberish,
      _fdcProofHash: BytesLike,
      _timestamp: BigNumberish,
      _backendSigner: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DecisionLogged"
  ): TypedContractEvent<
    DecisionLoggedEvent.InputTuple,
    DecisionLoggedEvent.OutputTuple,
    DecisionLoggedEvent.OutputObject
  >;

  filters: {
    "DecisionLogged(bytes32,bytes32,address,uint256,uint256,bytes32)": TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;
    DecisionLogged: TypedContractEvent<
      DecisionLoggedEvent.InputTuple,
      DecisionLoggedEvent.OutputTuple,
      DecisionLoggedEvent.OutputObject
    >;
  };
}
